# Generated by Django 4.0.2 on 2022-02-10 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='date',
            new_name='date_created',
        ),
    ]
