# Generated by Django 4.0.2 on 2022-02-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_date_plant_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='species',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
